[project]
name = "PlotNeuralNetPy"
version = "1.0.0"
dependencies = []
authors = [
    {name = "HarisIqbal88", email = "???@???.com"},
]
readme = "README.md"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"